### ISSUE TITLE
Error building posix@2.0.1 with Node v4.0.0 on Mac OS X 10.10

### ISSUE THREAD

**Issue by claudiopro** [ohmu/node-posix#39]
My configuration:

```
node v4.0.0
node-gyp v2.0.2
xcodebuild 5.0.1
gcc (GCC) 4.4.7
Apple LLVM version 5.0 (clang-500.2.79) (based on LLVM 3.3svn)
Target: x86_64-apple-darwin14.5.0
```

Output of `npm install posix`:

```bash
$ npm install posix
|
> posix@2.0.1 install /Users/delphine/Development/Git/node_modules/posix
> node-gyp rebuild

  CXX(target) Release/obj.target/posix/src/posix.o
In file included from ../src/posix.cc:1:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/delphine/.node-gyp/4.0.0/src/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t'
      (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/delphine/.node-gyp/4.0.0/src/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose
      const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/delphine/.node-gyp/4.0.0/src/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were
      provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/delphine/.node-gyp/4.0.0/src/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were
      provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/posix.cc:1:
../node_modules/nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/delphine/.node-gyp/4.0.0/deps/v8/include/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no
      known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/delphine/.node-gyp/4.0.0/deps/v8/include/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no
      known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/delphine/.node-gyp/4.0.0/deps/v8/include/v8.h:214:13: note: candidate template ignored: failed template argument deduction
  V8_INLINE Local(Local<S> that)
            ^
/Users/delphine/.node-gyp/4.0.0/deps/v8/include/v8.h:326:13: note: candidate template ignored: failed template argument deduction
  V8_INLINE Local(S* that)
            ^
In file included from ../src/posix.cc:1:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../src/posix.cc:77:30: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
        return NanThrowError(ErrnoException(errno, "setsid"));
                             ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/posix.cc:98:30: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
        return NanThrowError(ErrnoException(errno, "chroot: chdir: "));
                             ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/posix.cc:102:30: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
        return NanThrowError(ErrnoException(errno, "chroot"));
                             ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/posix.cc:164:30: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
        return NanThrowError(ErrnoException(errno, "getrlimit"));
                             ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/posix.cc:236:34: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
            return NanThrowError(ErrnoException(errno, "getrlimit"));
                                 ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/posix.cc:243:30: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
        return NanThrowError(ErrnoException(errno, "setrlimit"));
                             ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/posix.cc:262:34: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
            return NanThrowError(ErrnoException(errno, "getpwuid"));
                                 ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/posix.cc:268:34: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
            return NanThrowError(ErrnoException(errno, "getpwnam"));
                                 ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/posix.cc:303:34: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
            return NanThrowError(ErrnoException(errno, "getgrgid"));
                                 ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/posix.cc:309:34: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
            return NanThrowError(ErrnoException(errno, "getgrnam"));
                                 ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/posix.cc:348:30: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
        return NanThrowError(ErrnoException(errno, "initgroups"));
                             ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/posix.cc:362:30: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
        return NanThrowError(ErrnoException(errno, "seteuid"));
                             ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/posix.cc:376:30: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
        return NanThrowError(ErrnoException(errno, "setegid"));
                             ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/posix.cc:390:30: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
        return NanThrowError(ErrnoException(errno, "setregid"));
                             ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/posix.cc:404:30: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
        return NanThrowError(ErrnoException(errno, "setreuid"));
                             ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/posix.cc:546:30: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
        return NanThrowError(ErrnoException(errno, "gethostname"));
                             ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/posix.cc:567:30: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
        return NanThrowError(ErrnoException(errno, "sethostname"));
                             ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:100:45: note: 'ErrnoException' declared here
                inline v8::Local<v8::Value> ErrnoException(
                                            ^
/Users/delphine/.node-gyp/4.0.0/src/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
In file included from ../src/posix.cc:1:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/delphine/.node-gyp/4.0.0/src/node.h:42:
/Users/delphine/.node-gyp/4.0.0/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type
      'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/delphine/.node-gyp/4.0.0/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template specialization
      'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/posix.cc:1:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/delphine/.node-gyp/4.0.0/src/node.h:42:
/Users/delphine/.node-gyp/4.0.0/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type
      'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/delphine/.node-gyp/4.0.0/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template specialization
      'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/posix.cc:1:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/delphine/.node-gyp/4.0.0/src/node.h:42:
/Users/delphine/.node-gyp/4.0.0/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type
      'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/delphine/.node-gyp/4.0.0/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template specialization
      'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/posix.cc:1:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/delphine/.node-gyp/4.0.0/src/node.h:42:
/Users/delphine/.node-gyp/4.0.0/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type
      'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/delphine/.node-gyp/4.0.0/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template specialization
      'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
17 warnings and 9 errors generated.
make: *** [Release/obj.target/posix/src/posix.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/delphine/Development/Git/node_modules/posix
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "posix"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! posix@2.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the posix@2.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the posix package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls posix
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/delphine/Development/Git/npm-debug.log
```

**Comment by claudiopro** [comment]
Just compiled with node v0.12.7, it went fine:

```bash
$ nvm use v0.12.7
Now using node v0.12.7 (npm v2.11.3)
$ npm install posix
-
> posix@2.0.1 install /Users/delphine/Development/Git/claudiopro/nodeschool.github.io/node_modules/posix
> node-gyp rebuild

  CXX(target) Release/obj.target/posix/src/posix.o
  SOLINK_MODULE(target) Release/posix.node
posix@2.0.1 node_modules/posix
└── nan@1.8.4
```

**Comment by franck34** [comment]
@claudiopro we are speaking about node v4

**Comment by franck34** [comment]
got problem too compiling posix module with node v4.0.0 on centos too:

npm-debug.log:


```
0 info it worked if it ends with ok
1 verbose cli [ '/home/franck/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'posix',
1 verbose cli   '--save' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose install initial load of /home/franck/nctrld/package.json
5 warn package.json nctrld@0.0.0 No license field.
6 verbose installManyTop reading scoped package data from /home/franck/nctrld/node_modules/async/package.json
7 verbose installManyTop reading scoped package data from /home/franck/nctrld/node_modules/ioredis/package.json
8 verbose installManyTop reading scoped package data from /home/franck/nctrld/node_modules/minimist/package.json
9 verbose installManyTop reading scoped package data from /home/franck/nctrld/node_modules/sprintf/package.json
10 verbose installManyTop reading scoped package data from /home/franck/nctrld/node_modules/step/package.json
11 verbose installManyTop reading scoped package data from /home/franck/nctrld/node_modules/winston/package.json
12 verbose installManyTop reading scoped package data from /home/franck/nctrld/node_modules/xml-mapping/package.json
13 verbose readDependencies loading dependencies from /home/franck/nctrld/package.json
14 silly cache add args [ 'posix', null ]
15 verbose cache add spec posix
16 silly cache add parsed spec Result {
16 silly cache add   raw: 'posix',
16 silly cache add   scope: null,
16 silly cache add   name: 'posix',
16 silly cache add   rawSpec: '',
16 silly cache add   spec: '*',
16 silly cache add   type: 'range' }
17 silly addNamed posix@*
18 verbose addNamed "*" is a valid semver range for posix
19 silly addNameRange { name: 'posix', range: '*', hasData: false }
20 silly mapToRegistry name posix
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/posix
24 verbose addNameRange registry:https://registry.npmjs.org/posix not in flight; fetching
25 verbose request uri https://registry.npmjs.org/posix
26 verbose request no auth needed
27 info attempt registry request try #1 at 19:03:42
28 verbose request id 9aad850b2e7e8998
29 verbose etag "9JH8D4QY9TRNOWT27JDA08O8H"
30 http request GET https://registry.npmjs.org/posix
31 http 304 https://registry.npmjs.org/posix
32 silly get cb [ 304,
32 silly get   { date: 'Tue, 15 Sep 2015 17:03:39 GMT',
32 silly get     via: '1.1 varnish',
32 silly get     'cache-control': 'max-age=60',
32 silly get     etag: '"9JH8D4QY9TRNOWT27JDA08O8H"',
32 silly get     age: '0',
32 silly get     connection: 'keep-alive',
32 silly get     'x-served-by': 'cache-fra1232-FRA',
32 silly get     'x-cache': 'HIT',
32 silly get     'x-cache-hits': '1',
32 silly get     'x-timer': 'S1442336619.757111,VS0,VE105',
32 silly get     vary: 'Accept' } ]
33 verbose etag https://registry.npmjs.org/posix from cache
34 verbose get saving posix to /root/.npm/registry.npmjs.org/posix/.cache.json
35 silly addNameRange number 2 { name: 'posix', range: '*', hasData: true }
36 silly addNameRange versions [ 'posix',
36 silly addNameRange   [ '0.0.1',
36 silly addNameRange     '0.0.2',
36 silly addNameRange     '0.0.3',
36 silly addNameRange     '0.0.4',
36 silly addNameRange     '0.0.5',
36 silly addNameRange     '0.0.6',
36 silly addNameRange     '0.0.7',
36 silly addNameRange     '0.0.8',
36 silly addNameRange     '0.0.10',
36 silly addNameRange     '0.0.11',
36 silly addNameRange     '0.0.12',
36 silly addNameRange     '0.0.13',
36 silly addNameRange     '1.0.0',
36 silly addNameRange     '1.0.1',
36 silly addNameRange     '1.0.2',
36 silly addNameRange     '1.0.3',
36 silly addNameRange     '1.0.4',
36 silly addNameRange     '2.0.0',
36 silly addNameRange     '2.0.1' ] ]
37 silly addNamed posix@2.0.1
38 verbose addNamed "2.0.1" is a plain semver version for posix
39 silly cache afterAdd posix@2.0.1
40 verbose afterAdd /root/.npm/posix/2.0.1/package/package.json not in flight; writing
41 verbose afterAdd /root/.npm/posix/2.0.1/package/package.json written
42 silly install resolved [ { name: 'posix',
42 silly install resolved     version: '2.0.1',
42 silly install resolved     description: 'The missing POSIX system calls',
42 silly install resolved     keywords:
42 silly install resolved      [ 'posix',
42 silly install resolved        'rlimit',
42 silly install resolved        'getrlimit',
42 silly install resolved        'setrlimit',
42 silly install resolved        'ulimit',
42 silly install resolved        'setuid',
42 silly install resolved        'setgid',
42 silly install resolved        'seteuid',
42 silly install resolved        'setegid',
42 silly install resolved        'chroot',
42 silly install resolved        'setreuid',
42 silly install resolved        'setregid',
42 silly install resolved        'getpgrp',
42 silly install resolved        'setsid',
42 silly install resolved        'setpgid',
42 silly install resolved        'getpwnam',
42 silly install resolved        'getgrnam',
42 silly install resolved        'uid',
42 silly install resolved        'gid',
42 silly install resolved        'initgroups',
42 silly install resolved        'syslog',
42 silly install resolved        'setlogmask',
42 silly install resolved        'gethostname',
42 silly install resolved        'sethostname' ],
42 silly install resolved     homepage: 'http://github.com/melor/node-posix',
42 silly install resolved     repository: { type: 'git', url: 'git://github.com/melor/node-posix.git' },
42 silly install resolved     author: { name: 'Mika Eloranta', email: 'mel@ohmu.fi' },
42 silly install resolved     main: './lib/posix',
42 silly install resolved     dependencies: { nan: '~1.8.4' },
42 silly install resolved     scripts: { test: 'make test', install: 'node-gyp rebuild' },
42 silly install resolved     engines: { node: '>= 0.8.0' },
42 silly install resolved     gypfile: true,
42 silly install resolved     gitHead: 'd042aaf050ff927ce7bd6d5ec2bf93a20dc795c7',
42 silly install resolved     bugs: { url: 'https://github.com/melor/node-posix/issues' },
42 silly install resolved     _id: 'posix@2.0.1',
42 silly install resolved     _shasum: 'aad1ae80ad108fe24274006ea1f251f0a73fc3e8',
42 silly install resolved     _from: 'posix@*',
42 silly install resolved     _npmVersion: '2.7.5',
42 silly install resolved     _nodeVersion: '0.12.2',
42 silly install resolved     _npmUser: { name: 'mel', email: 'mel@ohmu.fi' },
42 silly install resolved     maintainers: [ [Object] ],
42 silly install resolved     dist:
42 silly install resolved      { shasum: 'aad1ae80ad108fe24274006ea1f251f0a73fc3e8',
42 silly install resolved        tarball: 'http://registry.npmjs.org/posix/-/posix-2.0.1.tgz' },
42 silly install resolved     directories: {},
42 silly install resolved     _resolved: 'https://registry.npmjs.org/posix/-/posix-2.0.1.tgz',
42 silly install resolved     readme: 'ERROR: No README data found!' } ]
43 info install posix@2.0.1 into /home/franck/nctrld
44 info installOne posix@2.0.1
45 verbose installOne of posix to /home/franck/nctrld not in flight; installing
46 verbose lock using /root/.npm/_locks/posix-77226dec40c0ec44.lock for /home/franck/nctrld/node_modules/posix
47 silly install write writing posix 2.0.1 to /home/franck/nctrld/node_modules/posix
48 verbose unbuild node_modules/posix
49 silly gentlyRm /home/franck/nctrld/node_modules/posix is being purged from base /home/franck/nctrld
50 verbose gentlyRm don't care about contents; nuking /home/franck/nctrld/node_modules/posix
51 verbose tar unpack /root/.npm/posix/2.0.1/package.tgz
52 verbose tar unpacking to /home/franck/nctrld/node_modules/posix
53 silly gentlyRm /home/franck/nctrld/node_modules/posix is being purged
54 verbose gentlyRm don't care about contents; nuking /home/franck/nctrld/node_modules/posix
55 silly gunzTarPerm modes [ '755', '644' ]
56 silly gunzTarPerm extractEntry package.json
57 silly gunzTarPerm extractEntry README.md
58 silly gunzTarPerm extractEntry LICENSE
59 silly gunzTarPerm extractEntry binding.gyp
60 silly gunzTarPerm extractEntry lib/posix/index.js
61 silly gunzTarPerm extractEntry src/posix.cc
62 silly gunzTarPerm extractEntry test/unit/test-chroot.js
63 silly gunzTarPerm extractEntry test/unit/test-gethostname.js
64 silly gunzTarPerm extractEntry test/unit/test-getppid.js
65 silly gunzTarPerm extractEntry test/unit/test-getpwnam.js
66 silly gunzTarPerm extractEntry test/unit/test-getrlimit.js
67 silly gunzTarPerm extractEntry test/unit/test-getgrnam.js
68 silly gunzTarPerm extractEntry test/unit/test-setegid.js
69 silly gunzTarPerm extractEntry test/unit/test-seteuid.js
70 silly gunzTarPerm extractEntry test/unit/test-setregid.js
71 silly gunzTarPerm extractEntry test/unit/test-setreuid.js
72 silly gunzTarPerm extractEntry test/unit/test-setrlimit.js
73 silly gunzTarPerm extractEntry test/unit/test-geteuid.js
74 silly gunzTarPerm extractEntry test/unit/test-setsid.js
75 silly gunzTarPerm extractEntry test/unit/test-getegid.js
76 silly gunzTarPerm extractEntry test/unit/test-syslog.js
77 silly gunzTarPerm extractEntry test/unit/test-initgroups.js
78 silly gunzTarPerm extractEntry wscript
79 verbose write writing to /home/franck/nctrld/node_modules/posix/package.json
80 info preinstall posix@2.0.1
81 verbose readDependencies loading dependencies from /home/franck/nctrld/node_modules/posix/package.json
82 silly prepareForInstallMany adding nan@~1.8.4 from posix dependencies
83 verbose readDependencies loading dependencies from /home/franck/nctrld/node_modules/posix/package.json
84 silly cache add args [ 'nan@~1.8.4', null ]
85 verbose cache add spec nan@~1.8.4
86 silly cache add parsed spec Result {
86 silly cache add   raw: 'nan@~1.8.4',
86 silly cache add   scope: null,
86 silly cache add   name: 'nan',
86 silly cache add   rawSpec: '~1.8.4',
86 silly cache add   spec: '>=1.8.4 <1.9.0',
86 silly cache add   type: 'range' }
87 silly addNamed nan@>=1.8.4 <1.9.0
88 verbose addNamed ">=1.8.4 <1.9.0" is a valid semver range for nan
89 silly addNameRange { name: 'nan', range: '>=1.8.4 <1.9.0', hasData: false }
90 silly mapToRegistry name nan
91 silly mapToRegistry using default registry
92 silly mapToRegistry registry https://registry.npmjs.org/
93 silly mapToRegistry uri https://registry.npmjs.org/nan
94 verbose addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
95 verbose request uri https://registry.npmjs.org/nan
96 verbose request no auth needed
97 info attempt registry request try #1 at 19:03:42
98 verbose etag "1L4RU1AM541YSVP1YQFXG1Y1J"
99 http request GET https://registry.npmjs.org/nan
100 http 304 https://registry.npmjs.org/nan
101 silly get cb [ 304,
101 silly get   { date: 'Tue, 15 Sep 2015 17:03:40 GMT',
101 silly get     via: '1.1 varnish',
101 silly get     'cache-control': 'max-age=60',
101 silly get     etag: '"1L4RU1AM541YSVP1YQFXG1Y1J"',
101 silly get     age: '37',
101 silly get     connection: 'keep-alive',
101 silly get     'x-served-by': 'cache-fra1242-FRA',
101 silly get     'x-cache': 'HIT',
101 silly get     'x-cache-hits': '1',
101 silly get     'x-timer': 'S1442336620.084357,VS0,VE0',
101 silly get     vary: 'Accept' } ]
102 verbose etag https://registry.npmjs.org/nan from cache
103 verbose get saving nan to /root/.npm/registry.npmjs.org/nan/.cache.json
104 silly addNameRange number 2 { name: 'nan', range: '>=1.8.4 <1.9.0', hasData: true }
105 silly addNameRange versions [ 'nan',
105 silly addNameRange   [ '0.3.0-wip',
105 silly addNameRange     '0.3.0-wip2',
105 silly addNameRange     '0.3.0',
105 silly addNameRange     '0.3.1',
105 silly addNameRange     '0.3.2',
105 silly addNameRange     '0.4.0',
105 silly addNameRange     '0.4.1',
105 silly addNameRange     '0.4.2',
105 silly addNameRange     '0.4.3',
105 silly addNameRange     '0.4.4',
105 silly addNameRange     '0.5.0',
105 silly addNameRange     '0.5.1',
105 silly addNameRange     '0.5.2',
105 silly addNameRange     '0.6.0',
105 silly addNameRange     '0.7.0',
105 silly addNameRange     '0.7.1',
105 silly addNameRange     '0.8.0',
105 silly addNameRange     '1.0.0',
105 silly addNameRange     '1.1.0',
105 silly addNameRange     '1.1.1',
105 silly addNameRange     '1.1.2',
105 silly addNameRange     '1.2.0',
105 silly addNameRange     '1.3.0',
105 silly addNameRange     '1.4.0',
105 silly addNameRange     '1.4.1',
105 silly addNameRange     '1.5.0',
105 silly addNameRange     '1.4.2',
105 silly addNameRange     '1.4.3',
105 silly addNameRange     '1.5.1',
105 silly addNameRange     '1.5.2',
105 silly addNameRange     '1.6.0',
105 silly addNameRange     '1.5.3',
105 silly addNameRange     '1.6.1',
105 silly addNameRange     '1.6.2',
105 silly addNameRange     '1.7.0',
105 silly addNameRange     '1.8.0',
105 silly addNameRange     '1.8.1',
105 silly addNameRange     '1.8.2',
105 silly addNameRange     '1.8.3',
105 silly addNameRange     '1.8.4',
105 silly addNameRange     '1.9.0',
105 silly addNameRange     '2.0.0',
105 silly addNameRange     '2.0.1',
105 silly addNameRange     '2.0.2',
105 silly addNameRange     '2.0.3',
105 silly addNameRange     '2.0.4',
105 silly addNameRange     '2.0.5',
105 silly addNameRange     '2.0.6',
105 silly addNameRange     '2.0.7',
105 silly addNameRange     '2.0.8',
105 silly addNameRange     '2.0.9' ] ]
106 silly addNamed nan@1.8.4
107 verbose addNamed "1.8.4" is a plain semver version for nan
108 silly cache afterAdd nan@1.8.4
109 verbose afterAdd /root/.npm/nan/1.8.4/package/package.json not in flight; writing
110 verbose afterAdd /root/.npm/nan/1.8.4/package/package.json written
111 silly install resolved [ { name: 'nan',
111 silly install resolved     version: '1.8.4',
111 silly install resolved     description: 'Native Abstractions for Node.js: C++ header for Node 0.8->0.12 compatibility',
111 silly install resolved     main: 'include_dirs.js',
111 silly install resolved     repository: { type: 'git', url: 'git://github.com/iojs/nan.git' },
111 silly install resolved     scripts:
111 silly install resolved      { test: 'tap --gc test/js/*-test.js',
111 silly install resolved        'rebuild-tests': 'pangyp rebuild --directory test' },
111 silly install resolved     contributors:
111 silly install resolved      [ [Object],
111 silly install resolved        [Object],
111 silly install resolved        [Object],
111 silly install resolved        [Object],
111 silly install resolved        [Object],
111 silly install resolved        [Object],
111 silly install resolved        [Object] ],
111 silly install resolved     devDependencies:
111 silly install resolved      { bindings: '~1.2.1',
111 silly install resolved        'node-gyp': '~1.0.2',
111 silly install resolved        pangyp: '~2.0.1',
111 silly install resolved        tap: '~0.7.1',
111 silly install resolved        xtend: '~4.0.0' },
111 silly install resolved     license: 'MIT',
111 silly install resolved     gitHead: 'ed3bbf4ced0cf7937b4e4164766797f71aa97f3d',
111 silly install resolved     bugs: { url: 'https://github.com/iojs/nan/issues' },
111 silly install resolved     homepage: 'https://github.com/iojs/nan#readme',
111 silly install resolved     _id: 'nan@1.8.4',
111 silly install resolved     _shasum: '3c76b5382eab33e44b758d2813ca9d92e9342f34',
111 silly install resolved     _from: 'nan@>=1.8.4 <1.9.0',
111 silly install resolved     _npmVersion: '2.8.3',
111 silly install resolved     _nodeVersion: '0.12.2',
111 silly install resolved     _npmUser: { name: 'kkoopa', email: 'bbyholm@abo.fi' },
111 silly install resolved     maintainers: [ [Object], [Object] ],
111 silly install resolved     dist:
111 silly install resolved      { shasum: '3c76b5382eab33e44b758d2813ca9d92e9342f34',
111 silly install resolved        tarball: 'http://registry.npmjs.org/nan/-/nan-1.8.4.tgz' },
111 silly install resolved     directories: {},
111 silly install resolved     _resolved: 'https://registry.npmjs.org/nan/-/nan-1.8.4.tgz',
111 silly install resolved     readme: 'ERROR: No README data found!' } ]
112 info install nan@1.8.4 into /home/franck/nctrld/node_modules/posix
113 info installOne nan@1.8.4
114 verbose installOne of nan to /home/franck/nctrld/node_modules/posix not in flight; installing
115 verbose lock using /root/.npm/_locks/nan-1169d088749197e5.lock for /home/franck/nctrld/node_modules/posix/node_modules/nan
116 silly install write writing nan 1.8.4 to /home/franck/nctrld/node_modules/posix/node_modules/nan
117 verbose unbuild node_modules/posix/node_modules/nan
122 silly gentlyRm /home/franck/nctrld/node_modules/posix/node_modules/nan is being purged
123 verbose gentlyRm don't care about contents; nuking /home/franck/nctrld/node_modules/posix/node_modules/nan
124 silly gunzTarPerm modes [ '755', '644' ]
125 silly gunzTarPerm extractEntry package.json
126 silly gunzTarPerm modified mode [ 'package.json', 436, 420 ]
127 silly gunzTarPerm extractEntry README.md
128 silly gunzTarPerm modified mode [ 'README.md', 436, 420 ]
129 silly gunzTarPerm extractEntry include_dirs.js
130 silly gunzTarPerm modified mode [ 'include_dirs.js', 436, 420 ]
131 silly gunzTarPerm extractEntry LICENSE.md
132 silly gunzTarPerm modified mode [ 'LICENSE.md', 436, 420 ]
133 silly gunzTarPerm extractEntry .dntrc
134 silly gunzTarPerm modified mode [ '.dntrc', 436, 420 ]
135 silly gunzTarPerm extractEntry appveyor.yml
136 silly gunzTarPerm modified mode [ 'appveyor.yml', 436, 420 ]
137 silly gunzTarPerm extractEntry nan.h
138 silly gunzTarPerm modified mode [ 'nan.h', 436, 420 ]
139 silly gunzTarPerm extractEntry nan_implementation_12_inl.h
140 silly gunzTarPerm modified mode [ 'nan_implementation_12_inl.h', 436, 420 ]
141 silly gunzTarPerm extractEntry nan_implementation_pre_12_inl.h
142 silly gunzTarPerm modified mode [ 'nan_implementation_pre_12_inl.h', 436, 420 ]
143 silly gunzTarPerm extractEntry nan_new.h
144 silly gunzTarPerm modified mode [ 'nan_new.h', 436, 420 ]
145 silly gunzTarPerm extractEntry nan_string_bytes.h
146 silly gunzTarPerm modified mode [ 'nan_string_bytes.h', 436, 420 ]
147 silly gunzTarPerm extractEntry CHANGELOG.md
148 silly gunzTarPerm modified mode [ 'CHANGELOG.md', 436, 420 ]
149 verbose write writing to /home/franck/nctrld/node_modules/posix/node_modules/nan/package.json
150 info preinstall nan@1.8.4
151 verbose readDependencies loading dependencies from /home/franck/nctrld/node_modules/posix/node_modules/nan/package.json
152 verbose readDependencies loading dependencies from /home/franck/nctrld/node_modules/posix/node_modules/nan/package.json
153 silly install resolved []
154 verbose about to build /home/franck/nctrld/node_modules/posix/node_modules/nan
155 info build /home/franck/nctrld/node_modules/posix/node_modules/nan
156 info linkStuff nan@1.8.4
157 silly linkStuff nan@1.8.4 has /home/franck/nctrld/node_modules/posix/node_modules as its parent node_modules
158 verbose linkBins nan@1.8.4
159 verbose linkMans nan@1.8.4
160 verbose rebuildBundles nan@1.8.4
161 info install nan@1.8.4
162 info postinstall nan@1.8.4
163 verbose unlock done using /root/.npm/_locks/nan-1169d088749197e5.lock for /home/franck/nctrld/node_modules/posix/node_modules/nan
164 verbose about to build /home/franck/nctrld/node_modules/posix
165 info build /home/franck/nctrld/node_modules/posix
166 info linkStuff posix@2.0.1
167 silly linkStuff posix@2.0.1 has /home/franck/nctrld/node_modules as its parent node_modules
168 verbose linkBins posix@2.0.1
169 verbose linkMans posix@2.0.1
170 verbose rebuildBundles posix@2.0.1
171 verbose rebuildBundles [ 'nan' ]
172 info install posix@2.0.1
173 verbose unsafe-perm in lifecycle false
174 info posix@2.0.1 Failed to exec install script
175 verbose unlock done using /root/.npm/_locks/posix-77226dec40c0ec44.lock for /home/franck/nctrld/node_modules/posix
176 verbose stack Error: posix@2.0.1 install: `node-gyp rebuild`
176 verbose stack Exit status 1
176 verbose stack     at EventEmitter.<anonymous> (/home/franck/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
176 verbose stack     at emitTwo (events.js:87:13)
176 verbose stack     at EventEmitter.emit (events.js:172:7)
176 verbose stack     at ChildProcess.<anonymous> (/home/franck/lib/node_modules/npm/lib/utils/spawn.js:24:14)
176 verbose stack     at emitTwo (events.js:87:13)
176 verbose stack     at ChildProcess.emit (events.js:172:7)
176 verbose stack     at maybeClose (internal/child_process.js:817:16)
176 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
177 verbose pkgid posix@2.0.1
178 verbose cwd /home/franck/nctrld
179 error Linux 3.10.0-229.11.1.el7.centos.x86_64
180 error argv "/home/franck/bin/node" "/usr/local/bin/npm" "install" "posix" "--save"
181 error node v4.0.0
182 error npm  v2.14.2
183 error code ELIFECYCLE
184 error posix@2.0.1 install: `node-gyp rebuild`
184 error Exit status 1
185 error Failed at the posix@2.0.1 install script 'node-gyp rebuild'.
185 error This is most likely a problem with the posix package,
185 error not with npm itself.
185 error Tell the author that this fails on your system:
185 error     node-gyp rebuild
185 error You can get their info via:
185 error     npm owner ls posix
185 error There is likely additional logging output above.
186 verbose exit [ 1, true ]
187 verbose unbuild node_modules/posix
188 info preuninstall posix@2.0.1
189 info uninstall posix@2.0.1
190 verbose unbuild rmStuff posix@2.0.1 from /home/franck/nctrld/node_modules
191 info postuninstall posix@2.0.1
192 silly gentlyRm /home/franck/nctrld/node_modules/posix is being purged from base /home/franck/nctrld
193 verbose gentlyRm don't care about contents; nuking /home/franck/nctrld/node_modules/posix
194 silly vacuum-fs purging /home/franck/nctrld/node_modules/posix
195 silly vacuum-fs quitting because other entries in /home/franck/nctrld/node_modules
```

**Comment by franck34** [comment]
@Ormod
@melor
@saaros 

Hi guys, thanks for this module !

Should be great if you take some time to make it compat with node 4 !

Thank You !

**Comment by franck34** [comment]
```

make: Entering directory `/home/franck/nctrld/node_modules/posix/build'
  CXX(target) Release/obj.target/posix/src/posix.o
In file included from ../src/posix.cc:1:0:
../node_modules/nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:256:25: error: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:672:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/posix.cc:1:
/home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/posix.cc:1:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:676:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../src/posix.cc: In function ‘void node_setsid(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:77:60: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated-
declarations]
         return NanThrowError(ErrnoException(errno, "setsid"));
                                                            ^
../src/posix.cc: In function ‘void node_chroot(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:98:69: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated-
declarations]
         return NanThrowError(ErrnoException(errno, "chroot: chdir: "));
                                                                     ^
../src/posix.cc:102:60: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated
-declarations]
         return NanThrowError(ErrnoException(errno, "chroot"));
                                                            ^
../src/posix.cc: In function ‘void node_getrlimit(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:164:63: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated
-declarations]
         return NanThrowError(ErrnoException(errno, "getrlimit"));
                                                               ^
../src/posix.cc: In function ‘void node_setrlimit(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:236:67: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated
-declarations]
             return NanThrowError(ErrnoException(errno, "getrlimit"));
                                                                   ^
../src/posix.cc:243:63: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated
-declarations]
         return NanThrowError(ErrnoException(errno, "setrlimit"));
                                                               ^
../src/posix.cc: In function ‘void node_getpwnam(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:262:66: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated
-declarations]
             return NanThrowError(ErrnoException(errno, "getpwuid"));
                                                                  ^
../src/posix.cc:268:66: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated
-declarations]
             return NanThrowError(ErrnoException(errno, "getpwnam"));
                                                                  ^
../src/posix.cc: In function ‘void node_getgrnam(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:303:66: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated
-declarations]
             return NanThrowError(ErrnoException(errno, "getgrgid"));
                                                                  ^
../src/posix.cc:309:66: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated
-declarations]
             return NanThrowError(ErrnoException(errno, "getgrnam"));
                                                                  ^
../src/posix.cc: In function ‘void node_initgroups(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:348:64: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated
-declarations]
         return NanThrowError(ErrnoException(errno, "initgroups"));
                                                                ^
../src/posix.cc: In function ‘void node_seteuid(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:362:61: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated
-declarations]
         return NanThrowError(ErrnoException(errno, "seteuid"));
                                                             ^
../src/posix.cc: In function ‘void node_setegid(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:376:61: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated
-declarations]
         return NanThrowError(ErrnoException(errno, "setegid"));
                                                             ^
../src/posix.cc: In function ‘void node_setregid(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:390:62: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated
-declarations]
         return NanThrowError(ErrnoException(errno, "setregid"));
                                                              ^
../src/posix.cc: In function ‘void node_setreuid(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:404:62: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated
-declarations]
         return NanThrowError(ErrnoException(errno, "setreuid"));
                                                              ^
../src/posix.cc: In function ‘void node_gethostname(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:546:65: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated
-declarations]
         return NanThrowError(ErrnoException(errno, "gethostname"));
                                                                 ^
../src/posix.cc: In function ‘void node_sethostname(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/posix.cc:567:65: warning: ‘v8::Local<v8::Value> node::ErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at /home/franck/nctrld/node_modules/posix/.node-gyp/4.0.0/include/node/node.h:99): Use UVException(isolate, ...) [-Wdeprecated-declarations]
         return NanThrowError(ErrnoException(errno, "sethostname"));
                                                                 ^
make: *** [Release/obj.target/posix/src/posix.o] Error 1
make: Leaving directory `/home/franck/nctrld/node_modules/posix/build'

```

**Comment by melor** [comment]
By popular request... posix@4.0.0, available at the usual places, should now work with node v4 and all past versions. Please reopen the ticket if there are further issues.

Thank you @robey for doing most of the v4 work!

**Comment by claudiopro** [comment]
@franck34 hey, yep - I added output of compilation with node v0.12.7 just as a reference.

@melor @robey thank you!

**Comment by feross** [comment]
Still seeing failures on linux (running on travis). See: https://travis-ci.org/feross/unlimited/jobs/80580135#L87

**Comment by feross** [comment]
Can someone reopen this issue?

**Comment by franck34** [comment]
@claudiopro ok thank you
@melor @robey big thank you, it's ok for me (linux/centos), really cool, that was the only one module in my project which was not compiling

**Comment by feross** [comment]
After further testing, it works fine for me on Ubuntu 14.04. Still doesn't build on Ubuntu 12.04, which is what Travis uses.
